define laser ranger
(
  sensor
  (
    range_max 30.0
    fov 360.0
    samples 640
  )
  # generic model properties
  color "black"
  size [ 0.05 0.05 0.05 ]
)

#
# Robot model:
# footprint (counter-clockwise): [-0.1,-0.125], [0.5,-0.125], [0.5,0.125], [-0.1,0.125]
# center of rotation: [0,0]
# wheelbase: 0.4

define carlike_robot position
(
  pose [ 0.0 0.0 0.0 0.0 ]

  odom_error [0.03 0.03 999999 999999 999999 0.02]

  size [ 1. 0.5 0.40 ] # this models the footprint (rectangular), but shifted such that the bottom-left corner is in [0,0]. The center of rotation now here at [0.5, 0.125, 0.2]
  # correct center of rotation:
  origin [ -0.5 0.0 0.0 0.0]
  gui_nose 1
  color "red"

  # kinematics
  drive "car"
  wheelbase -1. # distance between both axles
  
  # spawn sensors
  laser(pose [ -1.0 0.0 -0.3 0.0 ]) # let laser see the pallet
)
