geometry_msgs/PoseStamped[]     plan
OrientationConstraint           orientation_constraint
---
bool                            result
---
float64                         dtg
bool                            frame_exists

bool                            blocked
geometry_msgs/Point             point_blocked
